version: '3.8'

services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: behance_postgres
    restart: always
    environment:
      POSTGRES_USER: vladharin
      POSTGRES_PASSWORD: "2001"
      POSTGRES_DB: behance_tags_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Кэш и очереди Redis (Защищенный)
  redis:
    image: redis:7-alpine
    container_name: behance_redis
    restart: always
    # Устанавливаем пароль при запуске
    command: redis-server --requirepass "Bz8#pL2!kR9*zT4$mP1&qW7^xY3sM6vB"
    ports:
      # Теперь порт 6379 не торчит в интернет. 
      # Он доступен только твоему бэкенду внутри Docker и тебе лично на этом компьютере.
      - "127.0.0.1:6379:6379"

  # Наш NestJS бэкенд
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: behance_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://vladharin:2001@postgres:5432/behance_tags_db?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Прокидываем пароль в переменные окружения бэкенда
      - REDIS_PASSWORD=Bz8#pL2!kR9*zT4$mP1&qW7^xY3sM6vB
    depends_on:
      - postgres
      - redis

  prisma-studio:
    image: behance-tags-saas-back-api 
    working_dir: /app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5555:5555"
    command: npx prisma studio --browser none --hostname 0.0.0.0

volumes:
  postgres_data: