version: '3.8'

services:
  # Наша база данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: behance_postgres
    restart: always
    environment:
      POSTGRES_USER: vladharin
      POSTGRES_PASSWORD: "2001"
      POSTGRES_DB: behance_tags_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Кэш и очереди Redis
  redis:
    image: redis:7-alpine
    container_name: behance_redis
    restart: always
    ports:
      - "6379:6379"

  # Наш NestJS бэкенд
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: behance_api
    restart: always
    ports:
      - "3000:3000"
    environment:

      - PORT=3000
      - DATABASE_URL=postgresql://vladkharin:2001@postgres:5432/behance_tags_db?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROXY_HOST=proxy.asocks.com
      - PROXY_PORT=9000
      - PROXY_USERNAME=user_sub_xxxxxx
      - PROXY_PASSWORD=your_asocks_password
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: